//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpiDashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChartingSharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChartingSharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpiDashboard.ChartingSharedStrings", typeof(ChartingSharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area type:.
        /// </summary>
        public static string AREA_TYPE {
            get {
                return ResourceManager.GetString("AREA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar type:.
        /// </summary>
        public static string BAR_TYPE {
            get {
                return ResourceManager.GetString("BAR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart subtitle:.
        /// </summary>
        public static string CHART_SUBTITLE {
            get {
                return ResourceManager.GetString("CHART_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart title:.
        /// </summary>
        public static string CHART_TITLE {
            get {
                return ResourceManager.GetString("CHART_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette:.
        /// </summary>
        public static string COLOR_PALETTE {
            get {
                return ResourceManager.GetString("COLOR_PALETTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composition:.
        /// </summary>
        public static string COMPOSITION {
            get {
                return ResourceManager.GetString("COMPOSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different bar colors.
        /// </summary>
        public static string DIFF_BAR_COLORS {
            get {
                return ResourceManager.GetString("DIFF_BAR_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value:.
        /// </summary>
        public static string END_VALUE {
            get {
                return ResourceManager.GetString("END_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One graph for each value of:.
        /// </summary>
        public static string GRAPH_FOR_EACH_VALUE_OF_VARIABLE {
            get {
                return ResourceManager.GetString("GRAPH_FOR_EACH_VALUE_OF_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval:.
        /// </summary>
        public static string INTERVAL {
            get {
                return ResourceManager.GetString("INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string LEGEND_DOCK_VALUE_BOTTOM {
            get {
                return ResourceManager.GetString("LEGEND_DOCK_VALUE_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LEGEND_DOCK_VALUE_LEFT {
            get {
                return ResourceManager.GetString("LEGEND_DOCK_VALUE_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string LEGEND_DOCK_VALUE_RIGHT {
            get {
                return ResourceManager.GetString("LEGEND_DOCK_VALUE_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string LEGEND_DOCK_VALUE_TOP {
            get {
                return ResourceManager.GetString("LEGEND_DOCK_VALUE_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend font size:.
        /// </summary>
        public static string LEGEND_FONT_SIZE {
            get {
                return ResourceManager.GetString("LEGEND_FONT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend placement:.
        /// </summary>
        public static string LEGEND_PLACEMENT {
            get {
                return ResourceManager.GetString("LEGEND_PLACEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line dash style (Y2):.
        /// </summary>
        public static string LINE_DASH_STYLE_Y2 {
            get {
                return ResourceManager.GetString("LINE_DASH_STYLE_Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line thickness (Y2):.
        /// </summary>
        public static string LINE_THICKNESS_Y2 {
            get {
                return ResourceManager.GetString("LINE_THICKNESS_Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line type:.
        /// </summary>
        public static string LINE_TYPE {
            get {
                return ResourceManager.GetString("LINE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line type (Y2):.
        /// </summary>
        public static string LINE_TYPE_Y2 {
            get {
                return ResourceManager.GetString("LINE_TYPE_Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation:.
        /// </summary>
        public static string ORIENTATION {
            get {
                return ResourceManager.GetString("ORIENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors and styles.
        /// </summary>
        public static string PANEL_COLORS_AND_STYLES {
            get {
                return ResourceManager.GetString("PANEL_COLORS_AND_STYLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        public static string PANEL_LABELS {
            get {
                return ResourceManager.GetString("PANEL_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string PANEL_LEGEND {
            get {
                return ResourceManager.GetString("PANEL_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second y-axis type:.
        /// </summary>
        public static string SECOND_Y_AXIS_TYPE {
            get {
                return ResourceManager.GetString("SECOND_Y_AXIS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second y-axis variable:.
        /// </summary>
        public static string SECOND_Y_AXIS_VARIABLE {
            get {
                return ResourceManager.GetString("SECOND_Y_AXIS_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show annotations.
        /// </summary>
        public static string SHOW_ANNOTATIONS {
            get {
                return ResourceManager.GetString("SHOW_ANNOTATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show annotations (Y2).
        /// </summary>
        public static string SHOW_ANNOTATIONS_Y2 {
            get {
                return ResourceManager.GetString("SHOW_ANNOTATIONS_Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show grid lines.
        /// </summary>
        public static string SHOW_GRID_LINES {
            get {
                return ResourceManager.GetString("SHOW_GRID_LINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend.
        /// </summary>
        public static string SHOW_LEGEND {
            get {
                return ResourceManager.GetString("SHOW_LEGEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend border.
        /// </summary>
        public static string SHOW_LEGEND_BORDER {
            get {
                return ResourceManager.GetString("SHOW_LEGEND_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show variable names.
        /// </summary>
        public static string SHOW_VAR_NAMES {
            get {
                return ResourceManager.GetString("SHOW_VAR_NAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between bars:.
        /// </summary>
        public static string SPACE_BETWEEN_BARS {
            get {
                return ResourceManager.GetString("SPACE_BETWEEN_BARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value:.
        /// </summary>
        public static string START_VALUE {
            get {
                return ResourceManager.GetString("START_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step:.
        /// </summary>
        public static string STEP {
            get {
                return ResourceManager.GetString("STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency % (bottom).
        /// </summary>
        public static string TRANS_PCT_BOTTOM {
            get {
                return ResourceManager.GetString("TRANS_PCT_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency % (top).
        /// </summary>
        public static string TRANS_PCT_TOP {
            get {
                return ResourceManager.GetString("TRANS_PCT_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use reference values.
        /// </summary>
        public static string USE_REFERENCE_VALUES {
            get {
                return ResourceManager.GetString("USE_REFERENCE_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis angle:.
        /// </summary>
        public static string X_AXIS_ANGLE {
            get {
                return ResourceManager.GetString("X_AXIS_ANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis label:.
        /// </summary>
        public static string X_AXIS_LABEL {
            get {
                return ResourceManager.GetString("X_AXIS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-axis label type:.
        /// </summary>
        public static string X_AXIS_LABEL_TYPE {
            get {
                return ResourceManager.GetString("X_AXIS_LABEL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis format:.
        /// </summary>
        public static string Y_AXIS_FORMAT {
            get {
                return ResourceManager.GetString("Y_AXIS_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-axis label:.
        /// </summary>
        public static string Y_AXIS_LABEL {
            get {
                return ResourceManager.GetString("Y_AXIS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2-axis format:.
        /// </summary>
        public static string Y2_AXIS_FORMAT {
            get {
                return ResourceManager.GetString("Y2_AXIS_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2-axis label:.
        /// </summary>
        public static string Y2_AXIS_LABEL {
            get {
                return ResourceManager.GetString("Y2_AXIS_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2-axis legend title:.
        /// </summary>
        public static string Y2_AXIS_LEGEND_TITLE {
            get {
                return ResourceManager.GetString("Y2_AXIS_LEGEND_TITLE", resourceCulture);
            }
        }
    }
}
