//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpiDashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardSharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardSharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpiDashboard.DashboardSharedStrings", typeof(DashboardSharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable could not be removed. Check to make sure that no data filters and/or other variables are dependent on this variable..
        /// </summary>
        public static string CANNOT_REMOVE_VARIABLE {
            get {
                return ResourceManager.GetString("CANNOT_REMOVE_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source must be read before the canvas can be saved..
        /// </summary>
        public static string CANNOT_SAVE_CANVAS_NO_DATA_SOURCE {
            get {
                return ResourceManager.GetString("CANNOT_SAVE_CANVAS_NO_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string CANVAS_FILE_BROWSE {
            get {
                return ResourceManager.GetString("CANVAS_FILE_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Access - Available Canvas Files.
        /// </summary>
        public static string CANVAS_FILES_HEADER {
            get {
                return ResourceManager.GetString("CANVAS_FILES_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following canvas filters are in effect: {0}.
        /// </summary>
        public static string CANVAS_FILTERS_IN_EFFECT {
            get {
                return ResourceManager.GetString("CANVAS_FILTERS_IN_EFFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas file {0} loaded successfully..
        /// </summary>
        public static string CANVAS_LOADED {
            get {
                return ResourceManager.GetString("CANVAS_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberration detection chart.
        /// </summary>
        public static string CMENU_ADD_ABERRATION_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_ABERRATION_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Analysis gadget.
        /// </summary>
        public static string CMENU_ADD_ANALYSIS_GADGET {
            get {
                return ResourceManager.GetString("CMENU_ADD_ANALYSIS_GADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area chart.
        /// </summary>
        public static string CMENU_ADD_AREA_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_AREA_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string CMENU_ADD_CHARTS {
            get {
                return ResourceManager.GetString("CMENU_ADD_CHARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column chart.
        /// </summary>
        public static string CMENU_ADD_COLUMN_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_COLUMN_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined frequency.
        /// </summary>
        public static string CMENU_ADD_COMBINED_FREQUENCY {
            get {
                return ResourceManager.GetString("CMENU_ADD_COMBINED_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex sample frequencies.
        /// </summary>
        public static string CMENU_ADD_CSFREQ {
            get {
                return ResourceManager.GetString("CMENU_ADD_CSFREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex sample means.
        /// </summary>
        public static string CMENU_ADD_CSMEANS {
            get {
                return ResourceManager.GetString("CMENU_ADD_CSMEANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex sample tables.
        /// </summary>
        public static string CMENU_ADD_CSTABLES {
            get {
                return ResourceManager.GetString("CMENU_ADD_CSTABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi curve chart.
        /// </summary>
        public static string CMENU_ADD_EPICURVE_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_EPICURVE_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string CMENU_ADD_FREQUENCY {
            get {
                return ResourceManager.GetString("CMENU_ADD_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image gadget.
        /// </summary>
        public static string CMENU_ADD_IMAGE_GADGET {
            get {
                return ResourceManager.GetString("CMENU_ADD_IMAGE_GADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line chart.
        /// </summary>
        public static string CMENU_ADD_LINE_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_LINE_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line list.
        /// </summary>
        public static string CMENU_ADD_LINE_LIST {
            get {
                return ResourceManager.GetString("CMENU_ADD_LINE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear regression.
        /// </summary>
        public static string CMENU_ADD_LINEAR {
            get {
                return ResourceManager.GetString("CMENU_ADD_LINEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistic regression.
        /// </summary>
        public static string CMENU_ADD_LOGISTIC {
            get {
                return ResourceManager.GetString("CMENU_ADD_LOGISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched pair case-control.
        /// </summary>
        public static string CMENU_ADD_MATCHED_PAIR_CASE_CONTROL {
            get {
                return ResourceManager.GetString("CMENU_ADD_MATCHED_PAIR_CASE_CONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means.
        /// </summary>
        public static string CMENU_ADD_MEANS {
            get {
                return ResourceManager.GetString("CMENU_ADD_MEANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M x N / 2 x 2 table.
        /// </summary>
        public static string CMENU_ADD_MXN {
            get {
                return ResourceManager.GetString("CMENU_ADD_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add NutStat growth chart.
        /// </summary>
        public static string CMENU_ADD_NUTSTAT {
            get {
                return ResourceManager.GetString("CMENU_ADD_NUTSTAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pareto chart.
        /// </summary>
        public static string CMENU_ADD_PARETO_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_PARETO_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie chart.
        /// </summary>
        public static string CMENU_ADD_PIE_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_PIE_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add related data source....
        /// </summary>
        public static string CMENU_ADD_RELATED_DATA {
            get {
                return ResourceManager.GetString("CMENU_ADD_RELATED_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Report gadget.
        /// </summary>
        public static string CMENU_ADD_REPORT_GADGET {
            get {
                return ResourceManager.GetString("CMENU_ADD_REPORT_GADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter chart.
        /// </summary>
        public static string CMENU_ADD_SCATTER_CHART {
            get {
                return ResourceManager.GetString("CMENU_ADD_SCATTER_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple text box.
        /// </summary>
        public static string CMENU_ADD_SIMPLE_TEXT_GADGET {
            get {
                return ResourceManager.GetString("CMENU_ADD_SIMPLE_TEXT_GADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add StatCalc calculator.
        /// </summary>
        public static string CMENU_ADD_STATCALC {
            get {
                return ResourceManager.GetString("CMENU_ADD_STATCALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word cloud.
        /// </summary>
        public static string CMENU_ADD_WORD_CLOUD {
            get {
                return ResourceManager.GetString("CMENU_ADD_WORD_CLOUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced statistics.
        /// </summary>
        public static string CMENU_ADV_STATS {
            get {
                return ResourceManager.GetString("CMENU_ADV_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-arrange gadgets.
        /// </summary>
        public static string CMENU_AUTO_ARRANGE {
            get {
                return ResourceManager.GetString("CMENU_AUTO_ARRANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom gadgets.
        /// </summary>
        public static string CMENU_CUSTOM_GADGETS {
            get {
                return ResourceManager.GetString("CMENU_CUSTOM_GADGETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string CMENU_EXPORT_DATA {
            get {
                return ResourceManager.GetString("CMENU_EXPORT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        public static string CMENU_MS_EXCEL {
            get {
                return ResourceManager.GetString("CMENU_MS_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        public static string CMENU_MS_WORD {
            get {
                return ResourceManager.GetString("CMENU_MS_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open canvas....
        /// </summary>
        public static string CMENU_OPEN_CANVAS {
            get {
                return ResourceManager.GetString("CMENU_OPEN_CANVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas properties.
        /// </summary>
        public static string CMENU_PROPERTIES {
            get {
                return ResourceManager.GetString("CMENU_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh data source.
        /// </summary>
        public static string CMENU_REFRESH {
            get {
                return ResourceManager.GetString("CMENU_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Dashboard.
        /// </summary>
        public static string CMENU_RESET {
            get {
                return ResourceManager.GetString("CMENU_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save output as HTML.
        /// </summary>
        public static string CMENU_SAVE_AS_HTML {
            get {
                return ResourceManager.GetString("CMENU_SAVE_AS_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save canvas.
        /// </summary>
        public static string CMENU_SAVE_CANVAS {
            get {
                return ResourceManager.GetString("CMENU_SAVE_CANVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save canvas as....
        /// </summary>
        public static string CMENU_SAVE_CANVAS_AS {
            get {
                return ResourceManager.GetString("CMENU_SAVE_CANVAS_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send output to.
        /// </summary>
        public static string CMENU_SEND_OUTPUT_TO {
            get {
                return ResourceManager.GetString("CMENU_SEND_OUTPUT_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set data source.
        /// </summary>
        public static string CMENU_SET_DATA_SOURCE {
            get {
                return ResourceManager.GetString("CMENU_SET_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show data dictionary.
        /// </summary>
        public static string CMENU_SHOW_DATA_DICTIONARY {
            get {
                return ResourceManager.GetString("CMENU_SHOW_DATA_DICTIONARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95% CI Lower.
        /// </summary>
        public static string COL_HEADER_CI_LOWER {
            get {
                return ResourceManager.GetString("COL_HEADER_CI_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95% CI Upper.
        /// </summary>
        public static string COL_HEADER_CI_UPPER {
            get {
                return ResourceManager.GetString("COL_HEADER_CI_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cum. Percent.
        /// </summary>
        public static string COL_HEADER_CUMULATIVE_PERCENT {
            get {
                return ResourceManager.GetString("COL_HEADER_CUMULATIVE_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact 95% LCL.
        /// </summary>
        public static string COL_HEADER_EXACT_CI_LOWER {
            get {
                return ResourceManager.GetString("COL_HEADER_EXACT_CI_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact 95% UCL.
        /// </summary>
        public static string COL_HEADER_EXACT_CI_UPPER {
            get {
                return ResourceManager.GetString("COL_HEADER_EXACT_CI_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleiss 95% LCL.
        /// </summary>
        public static string COL_HEADER_FLEISS_CI_LOWER {
            get {
                return ResourceManager.GetString("COL_HEADER_FLEISS_CI_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleiss 95% UCL.
        /// </summary>
        public static string COL_HEADER_FLEISS_CI_UPPER {
            get {
                return ResourceManager.GetString("COL_HEADER_FLEISS_CI_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string COL_HEADER_FREQUENCY {
            get {
                return ResourceManager.GetString("COL_HEADER_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string COL_HEADER_PERCENT {
            get {
                return ResourceManager.GetString("COL_HEADER_PERCENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string COL_HEADER_VALUE {
            get {
                return ResourceManager.GetString("COL_HEADER_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A field with this name already exists..
        /// </summary>
        public static string CREATE_VAR_GROUP_FIELD_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("CREATE_VAR_GROUP_FIELD_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields specified in the group were not found and have been excluded..
        /// </summary>
        public static string CREATE_VAR_GROUP_FIELDS_NOT_FOUND {
            get {
                return ResourceManager.GetString("CREATE_VAR_GROUP_FIELDS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fields selected..
        /// </summary>
        public static string CREATE_VAR_GROUP_NO_FIELDS_SELECTED {
            get {
                return ResourceManager.GetString("CREATE_VAR_GROUP_NO_FIELDS_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group name has been specified..
        /// </summary>
        public static string CREATE_VAR_GROUP_NO_NAME_SPECIFIED {
            get {
                return ResourceManager.GetString("CREATE_VAR_GROUP_NO_NAME_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom SQL Query.
        /// </summary>
        public static string CUSTOM_QUERY {
            get {
                return ResourceManager.GetString("CUSTOM_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a data source now.
        /// </summary>
        public static string DASHBOARD_INTRO_SET_DATA_SOURCE {
            get {
                return ResourceManager.GetString("DASHBOARD_INTRO_SET_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click on the canvas to set a data source and add statistical gadgets. Or, open an existing dashboard canvas..
        /// </summary>
        public static string DASHBOARD_INTRO_TEXT {
            get {
                return ResourceManager.GetString("DASHBOARD_INTRO_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epi Info 7 Dashboard.
        /// </summary>
        public static string DASHBOARD_TITLE {
            get {
                return ResourceManager.GetString("DASHBOARD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing finished.
        /// </summary>
        public static string DATA_PROCESSING_FINISHED {
            get {
                return ResourceManager.GetString("DATA_PROCESSING_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields are boolean.
        ///Denominator = {0}.
        /// </summary>
        public static string DENOMINATOR_DESCRIPTION_BOOLEAN {
            get {
                return ResourceManager.GetString("DENOMINATOR_DESCRIPTION_BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields are not boolean.
        ///Denominator = {0}.
        /// </summary>
        public static string DENOMINATOR_DESCRIPTION_NON_BOOLEAN {
            get {
                return ResourceManager.GetString("DENOMINATOR_DESCRIPTION_NON_BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input detected..
        /// </summary>
        public static string ERROR_CANNOT_CONDITIONAL_ASSIGN_INVALID_INPUT {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_CONDITIONAL_ASSIGN_INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This existing field cannot be assigned to because of mis-matched data types. It is of type {0} while the selection in this dialog is of type {1}..
        /// </summary>
        public static string ERROR_CANNOT_CONDITIONAL_ASSIGN_TYPE_MISMATCH {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_CONDITIONAL_ASSIGN_TYPE_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem decrypting the connection information inside of this canvas. The connection string contained in this canvas may have been encrypted using a different set of keys..
        /// </summary>
        public static string ERROR_CANNOT_DECRYPT {
            get {
                return ResourceManager.GetString("ERROR_CANNOT_DECRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source for this canvas cannot be found: {0}.
        /// </summary>
        public static string ERROR_CANVAS_DATA_SOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_CANVAS_DATA_SOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An input/output exception occurred and the canvas could not be saved. Check to make sure the specified file is not in use and try again..
        /// </summary>
        public static string ERROR_CANVAS_SAVE_IO_EXCEPTION {
            get {
                return ResourceManager.GetString("ERROR_CANVAS_SAVE_IO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid xml input.
        /// </summary>
        public static string ERROR_CANVAS_XML_INVALID {
            get {
                return ResourceManager.GetString("ERROR_CANVAS_XML_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column {0} does not exist in this data set..
        /// </summary>
        public static string ERROR_COLUMN_DOESNT_EXIST {
            get {
                return ResourceManager.GetString("ERROR_COLUMN_DOESNT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source could not be set. If supplying a custom SQL query, check the query&apos;s syntax and try again..
        /// </summary>
        public static string ERROR_DATA_SOURCE_GENERIC {
            get {
                return ResourceManager.GetString("ERROR_DATA_SOURCE_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem accessing the data source that this canvas file is referencing. Please check to make sure that you have adequate permissions to the database and try again..
        /// </summary>
        public static string ERROR_DATA_SOURCE_PERMISSIONS {
            get {
                return ResourceManager.GetString("ERROR_DATA_SOURCE_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified data filter is no longer valid..
        /// </summary>
        public static string ERROR_FILTER_NO_LONGER_VALID {
            get {
                return ResourceManager.GetString("ERROR_FILTER_NO_LONGER_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form named &apos;{0}&apos; was not found in this project. Please make sure the project you are selecting to use with this canvas file contains the appropriate form..
        /// </summary>
        public static string ERROR_FORM_NOT_FOUND_FOR_CANVAS {
            get {
                return ResourceManager.GetString("ERROR_FORM_NOT_FOUND_FOR_CANVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are present in the selected field or fields..
        /// </summary>
        public static string ERROR_NO_DATA {
            get {
                return ResourceManager.GetString("ERROR_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified project file ({0}) that is associated with this canvas was not found. Please modify the canvas file to point to a valid Epi Info 7 project or select a new data source..
        /// </summary>
        public static string ERROR_PROJECT_NOT_FOUND_FOR_CANVAS {
            get {
                return ResourceManager.GetString("ERROR_PROJECT_NOT_FOUND_FOR_CANVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many distinct values in the crosstab (outcome) variable {0}. The number of distinct
        ///values is {1} and the limit is {2}..
        /// </summary>
        public static string ERROR_TOO_MANY_CROSSTAB_VALUES {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_CROSSTAB_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many distinct values in the stratification variable {0}. The number of distinct
        ///values is {1} and the limit is {2}..
        /// </summary>
        public static string ERROR_TOO_MANY_STRATA_VALUES {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_STRATA_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many distinct values in the variable {0}. The number of distinct
        ///values is {1} and the limit is {2}..
        /// </summary>
        public static string ERROR_TOO_MANY_VALUES {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many distinct values in the crosstab (outcome) variable {0}. The number of distinct
        ///values is {1} and the limit is {2}..
        /// </summary>
        public static string ERROR_TOO_MANY_VALUES_COMBINED_FREQ {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_VALUES_COMBINED_FREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many values in all of the fields.
        ///The value count is {0} and the limit is {1}. Please use data filters to narrow the number
        ///of records or select fewer fields for the group..
        /// </summary>
        public static string ERROR_TOO_MANY_VALUES_COMBINED_FREQ_EXT {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_VALUES_COMBINED_FREQ_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no values on which to run the combined frequency..
        /// </summary>
        public static string ERROR_ZERO_VALUES_COMBINED_FREQ {
            get {
                return ResourceManager.GetString("ERROR_ZERO_VALUES_COMBINED_FREQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no values on which to run the combined frequency or the variables in the group are not supported for this gadget..
        /// </summary>
        public static string ERROR_ZERO_VALUES_COMBINED_FREQ_EXT {
            get {
                return ResourceManager.GetString("ERROR_ZERO_VALUES_COMBINED_FREQ_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string EXPORT_BUTTON_BROWSE {
            get {
                return ResourceManager.GetString("EXPORT_BUTTON_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string EXPORT_BUTTON_CLOSE {
            get {
                return ResourceManager.GetString("EXPORT_BUTTON_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string EXPORT_BUTTON_EXPORT {
            get {
                return ResourceManager.GetString("EXPORT_BUTTON_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection information.
        /// </summary>
        public static string EXPORT_CONN_INFO {
            get {
                return ResourceManager.GetString("EXPORT_CONN_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination table.
        /// </summary>
        public static string EXPORT_DEST_TABLE {
            get {
                return ResourceManager.GetString("EXPORT_DEST_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields selected.
        /// </summary>
        public static string EXPORT_FIELD_COUNT {
            get {
                return ResourceManager.GetString("EXPORT_FIELD_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields to export:.
        /// </summary>
        public static string EXPORT_FIELDS_TO_EXPORT {
            get {
                return ResourceManager.GetString("EXPORT_FIELDS_TO_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output format.
        /// </summary>
        public static string EXPORT_OUTPUT_FORMAT {
            get {
                return ResourceManager.GetString("EXPORT_OUTPUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort variables by tab order.
        /// </summary>
        public static string EXPORT_SORT_BY_TAB_ORDER {
            get {
                return ResourceManager.GetString("EXPORT_SORT_BY_TAB_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        public static string EXPORT_WINDOW_TITLE {
            get {
                return ResourceManager.GetString("EXPORT_WINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination field name already exists as a column in this data set. Please use another name..
        /// </summary>
        public static string EXPRESSION_ASSIGN_DESTINATION_FIELD_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EXPRESSION_ASSIGN_DESTINATION_FIELD_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination field name already exists as a defined field with recoded values. Please use another field name..
        /// </summary>
        public static string EXPRESSION_ASSIGN_DESTINATION_FIELD_ALREADY_EXISTS_AS_RECODED {
            get {
                return ResourceManager.GetString("EXPRESSION_ASSIGN_DESTINATION_FIELD_ALREADY_EXISTS_AS_RECODED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination field is blank..
        /// </summary>
        public static string EXPRESSION_ASSIGN_DESTINATION_FIELD_BLANK {
            get {
                return ResourceManager.GetString("EXPRESSION_ASSIGN_DESTINATION_FIELD_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields, {1} records.
        /// </summary>
        public static string FIELD_AND_RECORD_COUNT {
            get {
                return ResourceManager.GetString("FIELD_AND_RECORD_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} fields.
        /// </summary>
        public static string FIELD_COUNT {
            get {
                return ResourceManager.GetString("FIELD_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter is not valid and has not been applied. Check the filter&apos;s syntax and try again..
        /// </summary>
        public static string FILTER_IS_INVALID {
            get {
                return ResourceManager.GetString("FILTER_IS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filter is valid and is now in effect..
        /// </summary>
        public static string FILTER_IS_VALID {
            get {
                return ResourceManager.GetString("FILTER_IS_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define 2x2 Value Mappings.
        /// </summary>
        public static string GADGET_2X2_VALUE_REMAPPING_BUTTON {
            get {
                return ResourceManager.GetString("GADGET_2X2_VALUE_REMAPPING_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberration.
        /// </summary>
        public static string GADGET_ABERRATION {
            get {
                return ResourceManager.GetString("GADGET_ABERRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string GADGET_ABERRATION_ACTUAL {
            get {
                return ResourceManager.GetString("GADGET_ABERRATION_ACTUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string GADGET_ABERRATION_COUNT {
            get {
                return ResourceManager.GetString("GADGET_ABERRATION_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string GADGET_ABERRATION_DATE {
            get {
                return ResourceManager.GetString("GADGET_ABERRATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string GADGET_ABERRATION_DIFF {
            get {
                return ResourceManager.GetString("GADGET_ABERRATION_DIFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string GADGET_ABERRATION_EXPECTED {
            get {
                return ResourceManager.GetString("GADGET_ABERRATION_EXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberrations found:.
        /// </summary>
        public static string GADGET_ABERRATIONS_FOUND {
            get {
                return ResourceManager.GetString("GADGET_ABERRATIONS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string GADGET_ADVANCED_OPTIONS {
            get {
                return ResourceManager.GetString("GADGET_ADVANCED_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display all list values.
        /// </summary>
        public static string GADGET_ALL_LIST_VALUES {
            get {
                return ResourceManager.GetString("GADGET_ALL_LIST_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break type:.
        /// </summary>
        public static string GADGET_BREAK_TYPE {
            get {
                return ResourceManager.GetString("GADGET_BREAK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 1:.
        /// </summary>
        public static string GADGET_BREAK1 {
            get {
                return ResourceManager.GetString("GADGET_BREAK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 2:.
        /// </summary>
        public static string GADGET_BREAK2 {
            get {
                return ResourceManager.GetString("GADGET_BREAK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 3:.
        /// </summary>
        public static string GADGET_BREAK3 {
            get {
                return ResourceManager.GetString("GADGET_BREAK3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 4:.
        /// </summary>
        public static string GADGET_BREAK4 {
            get {
                return ResourceManager.GetString("GADGET_BREAK4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break 5:.
        /// </summary>
        public static string GADGET_BREAK5 {
            get {
                return ResourceManager.GetString("GADGET_BREAK5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center horizontally.
        /// </summary>
        public static string GADGET_CENTER {
            get {
                return ResourceManager.GetString("GADGET_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Gradient:.
        /// </summary>
        public static string GADGET_COLOR_GRADIENT {
            get {
                return ResourceManager.GetString("GADGET_COLOR_GRADIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aberration Detection Properties.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_ABERRATION_DETECTION {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_ABERRATION_DETECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Properties.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_CHART {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_CHART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Frequency Properties.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_COMBINED_FREQUENCY {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_COMBINED_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_FREQUENCY {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means Properties.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_MEANS {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_MEANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosstabulation Properties.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_MXN {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_MXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Properties.
        /// </summary>
        public static string GADGET_CONFIG_TITLE_WORD_CLOUD {
            get {
                return ResourceManager.GetString("GADGET_CONFIG_TITLE_WORD_CLOUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} gadgets.
        /// </summary>
        public static string GADGET_COUNT {
            get {
                return ResourceManager.GetString("GADGET_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count (Optional):.
        /// </summary>
        public static string GADGET_COUNT_VARIABLE_OPT {
            get {
                return ResourceManager.GetString("GADGET_COUNT_VARIABLE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-tabulate by:.
        /// </summary>
        public static string GADGET_CROSSTAB_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_CROSSTAB_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only showing records matching the following criteria (in addition to canvas filters): {0}.
        /// </summary>
        public static string GADGET_CUSTOM_FILTER {
            get {
                return ResourceManager.GetString("GADGET_CUSTOM_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string GADGET_DATE_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_DATE_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process records this many days prior:.
        /// </summary>
        public static string GADGET_DAYS_PRIOR {
            get {
                return ResourceManager.GetString("GADGET_DAYS_PRIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimals to display:.
        /// </summary>
        public static string GADGET_DECIMALS_TO_DISPLAY {
            get {
                return ResourceManager.GetString("GADGET_DECIMALS_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal 2x2 summary.
        /// </summary>
        public static string GADGET_DISPLAY_2X2_SUMMARY_HORIZONTALLY {
            get {
                return ResourceManager.GetString("GADGET_DISPLAY_2X2_SUMMARY_HORIZONTALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display ANOVA statistics.
        /// </summary>
        public static string GADGET_DISPLAY_ANOVA {
            get {
                return ResourceManager.GetString("GADGET_DISPLAY_ANOVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display options.
        /// </summary>
        public static string GADGET_DISPLAY_OPTIONS {
            get {
                return ResourceManager.GetString("GADGET_DISPLAY_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display stratas horizontally.
        /// </summary>
        public static string GADGET_DISPLAY_STRATAS_HORIZONTALLY {
            get {
                return ResourceManager.GetString("GADGET_DISPLAY_STRATAS_HORIZONTALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All gadgets will be erased from the canvas. Proceed?.
        /// </summary>
        public static string GADGET_ERASE_ALL_FROM_CANVAS {
            get {
                return ResourceManager.GetString("GADGET_ERASE_ALL_FROM_CANVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure:.
        /// </summary>
        public static string GADGET_EXPOSURE_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_EXPOSURE_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency of:.
        /// </summary>
        public static string GADGET_FREQUENCY_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_FREQUENCY_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group field:.
        /// </summary>
        public static string GADGET_GROUP_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_GROUP_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        public static string GADGET_HEIGHT {
            get {
                return ResourceManager.GetString("GADGET_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include missing values.
        /// </summary>
        public static string GADGET_INCLUDE_MISSING {
            get {
                return ResourceManager.GetString("GADGET_INCLUDE_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator (Optional):.
        /// </summary>
        public static string GADGET_INDICATOR_VARIABLE_OPT {
            get {
                return ResourceManager.GetString("GADGET_INDICATOR_VARIABLE_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators (Optional):.
        /// </summary>
        public static string GADGET_INDICATOR_VARIABLES_OPT {
            get {
                return ResourceManager.GetString("GADGET_INDICATOR_VARIABLES_OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag time (days):.
        /// </summary>
        public static string GADGET_LAG_TIME_DAYS {
            get {
                return ResourceManager.GetString("GADGET_LAG_TIME_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list labels.
        /// </summary>
        public static string GADGET_LIST_LABELS {
            get {
                return ResourceManager.GetString("GADGET_LIST_LABELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;type&apos; attribute for one of the gadgets in the specified canvas file is not set properly. The loading of this canvas file has been aborted..
        /// </summary>
        public static string GADGET_LOAD_ERROR {
            get {
                return ResourceManager.GetString("GADGET_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main variable:.
        /// </summary>
        public static string GADGET_MAIN_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_MAIN_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max column name length:.
        /// </summary>
        public static string GADGET_MAX_COL_NAME_LENGTH {
            get {
                return ResourceManager.GetString("GADGET_MAX_COL_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max height:.
        /// </summary>
        public static string GADGET_MAX_HEIGHT {
            get {
                return ResourceManager.GetString("GADGET_MAX_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width of percent bar:.
        /// </summary>
        public static string GADGET_MAX_PERCENT_BAR_WIDTH {
            get {
                return ResourceManager.GetString("GADGET_MAX_PERCENT_BAR_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxium rows to display:.
        /// </summary>
        public static string GADGET_MAX_ROWS_TO_DISPLAY {
            get {
                return ResourceManager.GetString("GADGET_MAX_ROWS_TO_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max width:.
        /// </summary>
        public static string GADGET_MAX_WIDTH {
            get {
                return ResourceManager.GetString("GADGET_MAX_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means of:.
        /// </summary>
        public static string GADGET_MEANS_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_MEANS_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data are present in the selected field or fields..
        /// </summary>
        public static string GADGET_MSG_NO_DATA {
            get {
                return ResourceManager.GetString("GADGET_MSG_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.
        /// </summary>
        public static string GADGET_MSG_OPERATION_CANCELLED {
            get {
                return ResourceManager.GetString("GADGET_MSG_OPERATION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aberrations found..
        /// </summary>
        public static string GADGET_NO_ABERRATIONS_FOUND {
            get {
                return ResourceManager.GetString("GADGET_NO_ABERRATIONS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome is continuous.
        /// </summary>
        public static string GADGET_OUTCOME_CONTINUOUS {
            get {
                return ResourceManager.GetString("GADGET_OUTCOME_CONTINUOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome:.
        /// </summary>
        public static string GADGET_OUTCOME_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_OUTCOME_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output columns to display:.
        /// </summary>
        public static string GADGET_OUTPUT_COLUMNS_DISPLAY {
            get {
                return ResourceManager.GetString("GADGET_OUTPUT_COLUMNS_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse field:.
        /// </summary>
        public static string GADGET_PARSE_FIELD {
            get {
                return ResourceManager.GetString("GADGET_PARSE_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row / column percents.
        /// </summary>
        public static string GADGET_ROW_COL_PERCENTS {
            get {
                return ResourceManager.GetString("GADGET_ROW_COL_PERCENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string GADGET_RUN_BUTTON {
            get {
                return ResourceManager.GetString("GADGET_RUN_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show denominator.
        /// </summary>
        public static string GADGET_SHOW_DENOMINATOR {
            get {
                return ResourceManager.GetString("GADGET_SHOW_DENOMINATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart 2x2 table.
        /// </summary>
        public static string GADGET_SMART_2X2 {
            get {
                return ResourceManager.GetString("GADGET_SMART_2X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort high to low.
        /// </summary>
        public static string GADGET_SORT_HI_LOW {
            get {
                return ResourceManager.GetString("GADGET_SORT_HI_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Method:.
        /// </summary>
        public static string GADGET_SORT_METHOD {
            get {
                return ResourceManager.GetString("GADGET_SORT_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show strata summary only.
        /// </summary>
        public static string GADGET_STRATA_SUMMARY_ONLY {
            get {
                return ResourceManager.GetString("GADGET_STRATA_SUMMARY_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratify by:.
        /// </summary>
        public static string GADGET_STRATA_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_STRATA_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold (Std. Deviations):.
        /// </summary>
        public static string GADGET_THRESHOLD {
            get {
                return ResourceManager.GetString("GADGET_THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to treat as true:.
        /// </summary>
        public static string GADGET_TRUE_VALUE {
            get {
                return ResourceManager.GetString("GADGET_TRUE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value to treat as true is required when combine mode is Boolean..
        /// </summary>
        public static string GADGET_TRUE_VALUE_REQ {
            get {
                return ResourceManager.GetString("GADGET_TRUE_VALUE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional cell shading.
        /// </summary>
        public static string GADGET_USE_CONDITIONAL_CELL_SHADING {
            get {
                return ResourceManager.GetString("GADGET_USE_CONDITIONAL_CELL_SHADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use field prompt.
        /// </summary>
        public static string GADGET_USE_FIELD_PROMPT {
            get {
                return ResourceManager.GetString("GADGET_USE_FIELD_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string GADGET_WEIGHT_VARIABLE {
            get {
                return ResourceManager.GetString("GADGET_WEIGHT_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string GADGET_WIDTH {
            get {
                return ResourceManager.GetString("GADGET_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-click on canvas to add content..
        /// </summary>
        public static string INSTRUCTIONS {
            get {
                return ResourceManager.GetString("INSTRUCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished caching data locally. Right-click on canvas to add content..
        /// </summary>
        public static string INSTRUCTIONS_FINISHED_CACHING {
            get {
                return ResourceManager.GetString("INSTRUCTIONS_FINISHED_CACHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map image has been saved..
        /// </summary>
        public static string MAP_IMAGE_SAVED {
            get {
                return ResourceManager.GetString("MAP_IMAGE_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Map has been saved..
        /// </summary>
        public static string MAP_SAVED {
            get {
                return ResourceManager.GetString("MAP_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MENU_SAVE {
            get {
                return ResourceManager.GetString("MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string MENU_SAVE_AS {
            get {
                return ResourceManager.GetString("MENU_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Data Source.
        /// </summary>
        public static string MENU_SET_DATA_SOURCE {
            get {
                return ResourceManager.GetString("MENU_SET_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current canvas was saved to file {0}..
        /// </summary>
        public static string NOTIFICATION_CANVAS_SAVE {
            get {
                return ResourceManager.GetString("NOTIFICATION_CANVAS_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output has been saved..
        /// </summary>
        public static string OUTPUT_SAVED {
            get {
                return ResourceManager.GetString("OUTPUT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend font size must be between 5 and 100..
        /// </summary>
        public static string PROPERTIES_LEGEND_FONT_SIZE_INVALID {
            get {
                return ResourceManager.GetString("PROPERTIES_LEGEND_FONT_SIZE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main variable must be selected..
        /// </summary>
        public static string PROPERTIES_MAIN_VARIABLE_REQ {
            get {
                return ResourceManager.GetString("PROPERTIES_MAIN_VARIABLE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome variable must be selected..
        /// </summary>
        public static string PROPERTIES_OUTCOME_VARIABLE_REQ {
            get {
                return ResourceManager.GetString("PROPERTIES_OUTCOME_VARIABLE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis font size must be between 5 and 100..
        /// </summary>
        public static string PROPERTIES_XAXIS_FONT_SIZE_INVALID {
            get {
                return ResourceManager.GetString("PROPERTIES_XAXIS_FONT_SIZE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second y-axis variable must be selected for this y-axis type..
        /// </summary>
        public static string PROPERTIES_Y2_AXIS_VARIABLE_REQ {
            get {
                return ResourceManager.GetString("PROPERTIES_Y2_AXIS_VARIABLE_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis font size must be between 5 and 100..
        /// </summary>
        public static string PROPERTIES_YAXIS_FONT_SIZE_INVALID {
            get {
                return ResourceManager.GetString("PROPERTIES_YAXIS_FONT_SIZE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} records).
        /// </summary>
        public static string RECORD_COUNT {
            get {
                return ResourceManager.GetString("RECORD_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exposure and outcome are boolean. No remapping is needed..
        /// </summary>
        public static string REMAPPER_MESSAGE_ALREADY_BOOLEAN {
            get {
                return ResourceManager.GetString("REMAPPER_MESSAGE_ALREADY_BOOLEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save the changes you made to this dashboard canvas?.
        /// </summary>
        public static string SAVE_CHANGES {
            get {
                return ResourceManager.GetString("SAVE_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save the changes you made to {0}?.
        /// </summary>
        public static string SAVE_CHANGES_TO_FILE {
            get {
                return ResourceManager.GetString("SAVE_CHANGES_TO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successful.
        /// </summary>
        public static string SAVE_SUCCESSFUL {
            get {
                return ResourceManager.GetString("SAVE_SUCCESSFUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected.
        /// </summary>
        public static string TABLES_CORRECTED {
            get {
                return ResourceManager.GetString("TABLES_CORRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string TABLES_ESTIMATE {
            get {
                return ResourceManager.GetString("TABLES_ESTIMATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisher-Exact.
        /// </summary>
        public static string TABLES_FISHER_EXACT {
            get {
                return ResourceManager.GetString("TABLES_FISHER_EXACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower.
        /// </summary>
        public static string TABLES_LOWER {
            get {
                return ResourceManager.GetString("TABLES_LOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantel-Haenszel.
        /// </summary>
        public static string TABLES_MH {
            get {
                return ResourceManager.GetString("TABLES_MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-P Exact.
        /// </summary>
        public static string TABLES_MIDP_EXACT {
            get {
                return ResourceManager.GetString("TABLES_MIDP_EXACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLE Odds ratio (Mid-P).
        /// </summary>
        public static string TABLES_MLE_ODDS_RATIO {
            get {
                return ResourceManager.GetString("TABLES_MLE_ODDS_RATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds ratio.
        /// </summary>
        public static string TABLES_ODDS_RATIO {
            get {
                return ResourceManager.GetString("TABLES_ODDS_RATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds- and Risk-based parameters.
        /// </summary>
        public static string TABLES_ODDS_RISK_PARAMS {
            get {
                return ResourceManager.GetString("TABLES_ODDS_RISK_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk difference.
        /// </summary>
        public static string TABLES_RISK_DIFFERENCE {
            get {
                return ResourceManager.GetString("TABLES_RISK_DIFFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk ratio.
        /// </summary>
        public static string TABLES_RISK_RATIO {
            get {
                return ResourceManager.GetString("TABLES_RISK_RATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Table Analysis.
        /// </summary>
        public static string TABLES_SINGLE_TABLE_ANALYSIS_HEADER {
            get {
                return ResourceManager.GetString("TABLES_SINGLE_TABLE_ANALYSIS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Tests.
        /// </summary>
        public static string TABLES_STATISTICAL_TESTS {
            get {
                return ResourceManager.GetString("TABLES_STATISTICAL_TESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncorrected.
        /// </summary>
        public static string TABLES_UNCORRECTED {
            get {
                return ResourceManager.GetString("TABLES_UNCORRECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper.
        /// </summary>
        public static string TABLES_UPPER {
            get {
                return ResourceManager.GetString("TABLES_UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the gadget..
        /// </summary>
        public static string TOOLTIP_CLOSE_GADGET {
            get {
                return ResourceManager.GetString("TOOLTIP_CLOSE_GADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapses or expands the gadget&apos;s output..
        /// </summary>
        public static string TOOLTIP_COLLAPSE_GADGET {
            get {
                return ResourceManager.GetString("TOOLTIP_COLLAPSE_GADGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the gadget configuration panel..
        /// </summary>
        public static string TOOLTIP_GADGET_CONFIG {
            get {
                return ResourceManager.GetString("TOOLTIP_GADGET_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the use of custom gadget-specific data filters. Any data filters created for this gadget will be applied in addition to any canvas-wide filters..
        /// </summary>
        public static string TOOLTIP_GADGET_DATA_FILTERS {
            get {
                return ResourceManager.GetString("TOOLTIP_GADGET_DATA_FILTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expands the description panel..
        /// </summary>
        public static string TOOLTIP_GADGET_DESC_PANEL {
            get {
                return ResourceManager.GetString("TOOLTIP_GADGET_DESC_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens an existing Dashboard canvas file..
        /// </summary>
        public static string TOOLTIP_MENU_OPEN {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Button.
        /// </summary>
        public static string TOOLTIP_MENU_OPEN_HEADER {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_OPEN_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates and refreshes the current data source..
        /// </summary>
        public static string TOOLTIP_MENU_REFRESH {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Button.
        /// </summary>
        public static string TOOLTIP_MENU_REFRESH_HEADER {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_REFRESH_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current Dashboard canvas..
        /// </summary>
        public static string TOOLTIP_MENU_SAVE {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current Dashboard canvas to a different file..
        /// </summary>
        public static string TOOLTIP_MENU_SAVE_AS {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Button.
        /// </summary>
        public static string TOOLTIP_MENU_SAVE_AS_HEADER {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_SAVE_AS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Button.
        /// </summary>
        public static string TOOLTIP_MENU_SAVE_HEADER {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_SAVE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaches a data source (Epi Info 7 project, Excel spreadsheet, etc.) to a new, blank Dashboard canvas..
        /// </summary>
        public static string TOOLTIP_MENU_SET_DATA_SOURCE {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_SET_DATA_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Data Source Button.
        /// </summary>
        public static string TOOLTIP_MENU_SET_DATA_SOURCE_HEADER {
            get {
                return ResourceManager.GetString("TOOLTIP_MENU_SET_DATA_SOURCE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaps the row positions for the exposure values. For example, if &apos;F&apos; were on the top and &apos;T&apos; were on the bottom, they would be switched..
        /// </summary>
        public static string TOOLTIP_SWAP_EXPOSURE {
            get {
                return ResourceManager.GetString("TOOLTIP_SWAP_EXPOSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swaps the column positions for the outcome values. For example, if &apos;F&apos; were on the left and &apos;T&apos; were on the right, they would be switched..
        /// </summary>
        public static string TOOLTIP_SWAP_OUTCOME {
            get {
                return ResourceManager.GetString("TOOLTIP_SWAP_OUTCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Conditional Assignment.
        /// </summary>
        public static string VARIABLE_CONTROL_CMENU_CONDITIONAL_ASSIGN {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_CMENU_CONDITIONAL_ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Assigned Expression.
        /// </summary>
        public static string VARIABLE_CONTROL_CMENU_EXPRESSION {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_CMENU_EXPRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Formatted Value.
        /// </summary>
        public static string VARIABLE_CONTROL_CMENU_FORMAT {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_CMENU_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Variable Group.
        /// </summary>
        public static string VARIABLE_CONTROL_CMENU_GROUP {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_CMENU_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Recoded Value.
        /// </summary>
        public static string VARIABLE_CONTROL_CMENU_RECODE {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_CMENU_RECODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Simple Assignment.
        /// </summary>
        public static string VARIABLE_CONTROL_CMENU_SIMPLE_ASSIGN {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_CMENU_SIMPLE_ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Variable.
        /// </summary>
        public static string VARIABLE_CONTROL_DEL_VARIABLE {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_DEL_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Variable.
        /// </summary>
        public static string VARIABLE_CONTROL_EDIT_VARIABLE {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_EDIT_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Definitions:.
        /// </summary>
        public static string VARIABLE_CONTROL_HEADER {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Variable.
        /// </summary>
        public static string VARIABLE_CONTROL_NEW_VARIABLE {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_NEW_VARIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined Variables ({0}).
        /// </summary>
        public static string VARIABLE_CONTROL_TITLE {
            get {
                return ResourceManager.GetString("VARIABLE_CONTROL_TITLE", resourceCulture);
            }
        }
    }
}
