//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Windows.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuSharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuSharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epi.Windows.Menu.MenuSharedStrings", typeof(MenuSharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANALYZE DATA.
        /// </summary>
        internal static string MENU_ANALYZE_DATA {
            get {
                return ResourceManager.GetString("MENU_ANALYZE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLASSIC.
        /// </summary>
        internal static string MENU_CLASSIC_ANALYZE {
            get {
                return ResourceManager.GetString("MENU_CLASSIC_ANALYZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean, transform, and analyze data with commands..
        /// </summary>
        internal static string MENU_CLASSIC_ANALYZEDSCP {
            get {
                return ResourceManager.GetString("MENU_CLASSIC_ANALYZEDSCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT HELP DESK.
        /// </summary>
        internal static string MENU_CONTACT_HELP_DESK {
            get {
                return ResourceManager.GetString("MENU_CONTACT_HELP_DESK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTENTS.
        /// </summary>
        internal static string MENU_CONTENT {
            get {
                return ResourceManager.GetString("MENU_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FORMS.
        /// </summary>
        internal static string MENU_CREATE_FORMS {
            get {
                return ResourceManager.GetString("MENU_CREATE_FORMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create surveys or questionnaires with field validation and skip logic..
        /// </summary>
        internal static string MENU_CREATE_FORMS_DESCP {
            get {
                return ResourceManager.GetString("MENU_CREATE_FORMS_DESCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE MAPS.
        /// </summary>
        internal static string MENU_CREATE_MAPS {
            get {
                return ResourceManager.GetString("MENU_CREATE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map data with coordinates, by choropleth, or dot density..
        /// </summary>
        internal static string MENU_CREATE_MAPS_DESCP {
            get {
                return ResourceManager.GetString("MENU_CREATE_MAPS_DESCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER DATA.
        /// </summary>
        internal static string MENU_ENTER_DATA {
            get {
                return ResourceManager.GetString("MENU_ENTER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter data, browse records, and search the database..
        /// </summary>
        internal static string MENU_ENTER_DATA_DESCP {
            get {
                return ResourceManager.GetString("MENU_ENTER_DATA_DESCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPI INFO™ LOGS.
        /// </summary>
        internal static string MENU_EPI_INFO_LOGS {
            get {
                return ResourceManager.GetString("MENU_EPI_INFO_LOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPI INFO™ Q&amp;A.
        /// </summary>
        internal static string MENU_EPI_INFO_QA {
            get {
                return ResourceManager.GetString("MENU_EPI_INFO_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO&apos; VIDEOS.
        /// </summary>
        internal static string MENU_HOW_TO_VIDEOS {
            get {
                return ResourceManager.GetString("MENU_HOW_TO_VIDEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        internal static string MENU_LANGUAGE {
            get {
                return ResourceManager.GetString("MENU_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        internal static string MENU_OPTIONS {
            get {
                return ResourceManager.GetString("MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER EPI RESOURCES.
        /// </summary>
        internal static string MENU_OTHER_RESOURCES {
            get {
                return ResourceManager.GetString("MENU_OTHER_RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATCALC.
        /// </summary>
        internal static string MENU_STATCALC {
            get {
                return ResourceManager.GetString("MENU_STATCALC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical calculators for sample size, power, and more..
        /// </summary>
        internal static string MENU_STATCALC_DESCP {
            get {
                return ResourceManager.GetString("MENU_STATCALC_DESCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUAL DASHBOARD.
        /// </summary>
        internal static string MENU_VISUALDASHBOARD {
            get {
                return ResourceManager.GetString("MENU_VISUALDASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualize analytical results with gadgets, charts, and tables..
        /// </summary>
        internal static string MENU_VISUALDASHBOARD_DESCP {
            get {
                return ResourceManager.GetString("MENU_VISUALDASHBOARD_DESCP", resourceCulture);
            }
        }
    }
}
