//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.ImportExport.SurveyManagerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.OrganizationRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.SurveyAnswerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.PublishRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LoadOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LoadOptions {
            get {
                return this.LoadOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadOptionsField, value) != true)) {
                    this.LoadOptionsField = value;
                    this.RaisePropertyChanged("LoadOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyInfoRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyInfoRequest : Epi.ImportExport.SurveyManagerService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyInfoCriteria CriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyInfoDTO[] SurveyInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyInfoCriteria Criteria {
            get {
                return this.CriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CriteriaField, value) != true)) {
                    this.CriteriaField = value;
                    this.RaisePropertyChanged("Criteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyInfoDTO[] SurveyInfoList {
            get {
                return this.SurveyInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyInfoListField, value) != true)) {
                    this.SurveyInfoListField = value;
                    this.RaisePropertyChanged("SurveyInfoList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class OrganizationRequest : Epi.ImportExport.SurveyManagerService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AdminSecurityKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.OrganizationDTO OrganizationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AdminSecurityKey {
            get {
                return this.AdminSecurityKeyField;
            }
            set {
                if ((this.AdminSecurityKeyField.Equals(value) != true)) {
                    this.AdminSecurityKeyField = value;
                    this.RaisePropertyChanged("AdminSecurityKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.OrganizationDTO Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyAnswerRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyAnswerRequest : Epi.ImportExport.SurveyManagerService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyAnswerCriteria CriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyAnswerDTO[] SurveyAnswerListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyAnswerCriteria Criteria {
            get {
                return this.CriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CriteriaField, value) != true)) {
                    this.CriteriaField = value;
                    this.RaisePropertyChanged("Criteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyAnswerDTO[] SurveyAnswerList {
            get {
                return this.SurveyAnswerListField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyAnswerListField, value) != true)) {
                    this.SurveyAnswerListField = value;
                    this.RaisePropertyChanged("SurveyAnswerList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublishRequest", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class PublishRequest : Epi.ImportExport.SurveyManagerService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyInfoDTO SurveyInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyInfoDTO SurveyInfo {
            get {
                return this.SurveyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyInfoField, value) != true)) {
                    this.SurveyInfoField = value;
                    this.RaisePropertyChanged("SurveyInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyInfoDTO", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClosingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IntroductionTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDraftModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSqlProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserPublishKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViewIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClosingDate {
            get {
                return this.ClosingDateField;
            }
            set {
                if ((this.ClosingDateField.Equals(value) != true)) {
                    this.ClosingDateField = value;
                    this.RaisePropertyChanged("ClosingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBConnectionString {
            get {
                return this.DBConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.DBConnectionStringField, value) != true)) {
                    this.DBConnectionStringField = value;
                    this.RaisePropertyChanged("DBConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitText {
            get {
                return this.ExitTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitTextField, value) != true)) {
                    this.ExitTextField = value;
                    this.RaisePropertyChanged("ExitText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IntroductionText {
            get {
                return this.IntroductionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.IntroductionTextField, value) != true)) {
                    this.IntroductionTextField = value;
                    this.RaisePropertyChanged("IntroductionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDraftMode {
            get {
                return this.IsDraftModeField;
            }
            set {
                if ((this.IsDraftModeField.Equals(value) != true)) {
                    this.IsDraftModeField = value;
                    this.RaisePropertyChanged("IsDraftMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSqlProject {
            get {
                return this.IsSqlProjectField;
            }
            set {
                if ((this.IsSqlProjectField.Equals(value) != true)) {
                    this.IsSqlProjectField = value;
                    this.RaisePropertyChanged("IsSqlProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationKey {
            get {
                return this.OrganizationKeyField;
            }
            set {
                if ((this.OrganizationKeyField.Equals(value) != true)) {
                    this.OrganizationKeyField = value;
                    this.RaisePropertyChanged("OrganizationKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdField, value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyId {
            get {
                return this.SurveyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyIdField, value) != true)) {
                    this.SurveyIdField = value;
                    this.RaisePropertyChanged("SurveyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyName {
            get {
                return this.SurveyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyNameField, value) != true)) {
                    this.SurveyNameField = value;
                    this.RaisePropertyChanged("SurveyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyNumber {
            get {
                return this.SurveyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyNumberField, value) != true)) {
                    this.SurveyNumberField = value;
                    this.RaisePropertyChanged("SurveyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyType {
            get {
                return this.SurveyTypeField;
            }
            set {
                if ((this.SurveyTypeField.Equals(value) != true)) {
                    this.SurveyTypeField = value;
                    this.RaisePropertyChanged("SurveyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserPublishKey {
            get {
                return this.UserPublishKeyField;
            }
            set {
                if ((this.UserPublishKeyField.Equals(value) != true)) {
                    this.UserPublishKeyField = value;
                    this.RaisePropertyChanged("UserPublishKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewId {
            get {
                return this.ViewIdField;
            }
            set {
                if ((this.ViewIdField.Equals(value) != true)) {
                    this.ViewIdField = value;
                    this.RaisePropertyChanged("ViewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XML {
            get {
                return this.XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLField, value) != true)) {
                    this.XMLField = value;
                    this.RaisePropertyChanged("XML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyInfoCriteria", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyInfoCriteria : Epi.ImportExport.SurveyManagerService.Criteria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClosingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.HttpPostedFileBase FileInputStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeOrderStatisticsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDraftModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnSizeInfoOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SurveyIdListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurveyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserPublishKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClosingDate {
            get {
                return this.ClosingDateField;
            }
            set {
                if ((this.ClosingDateField.Equals(value) != true)) {
                    this.ClosingDateField = value;
                    this.RaisePropertyChanged("ClosingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.HttpPostedFileBase FileInputStream {
            get {
                return this.FileInputStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.FileInputStreamField, value) != true)) {
                    this.FileInputStreamField = value;
                    this.RaisePropertyChanged("FileInputStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeOrderStatistics {
            get {
                return this.IncludeOrderStatisticsField;
            }
            set {
                if ((this.IncludeOrderStatisticsField.Equals(value) != true)) {
                    this.IncludeOrderStatisticsField = value;
                    this.RaisePropertyChanged("IncludeOrderStatistics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDraftMode {
            get {
                return this.IsDraftModeField;
            }
            set {
                if ((this.IsDraftModeField.Equals(value) != true)) {
                    this.IsDraftModeField = value;
                    this.RaisePropertyChanged("IsDraftMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationKey {
            get {
                return this.OrganizationKeyField;
            }
            set {
                if ((this.OrganizationKeyField.Equals(value) != true)) {
                    this.OrganizationKeyField = value;
                    this.RaisePropertyChanged("OrganizationKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnSizeInfoOnly {
            get {
                return this.ReturnSizeInfoOnlyField;
            }
            set {
                if ((this.ReturnSizeInfoOnlyField.Equals(value) != true)) {
                    this.ReturnSizeInfoOnlyField = value;
                    this.RaisePropertyChanged("ReturnSizeInfoOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SurveyIdList {
            get {
                return this.SurveyIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyIdListField, value) != true)) {
                    this.SurveyIdListField = value;
                    this.RaisePropertyChanged("SurveyIdList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurveyType {
            get {
                return this.SurveyTypeField;
            }
            set {
                if ((this.SurveyTypeField.Equals(value) != true)) {
                    this.SurveyTypeField = value;
                    this.RaisePropertyChanged("SurveyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserPublishKey {
            get {
                return this.UserPublishKeyField;
            }
            set {
                if ((this.UserPublishKeyField.Equals(value) != true)) {
                    this.UserPublishKeyField = value;
                    this.RaisePropertyChanged("UserPublishKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Criteria", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.SurveyAnswerCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.SurveyInfoCriteria))]
    public partial class Criteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortExpressionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortExpression {
            get {
                return this.SortExpressionField;
            }
            set {
                if ((object.ReferenceEquals(this.SortExpressionField, value) != true)) {
                    this.SortExpressionField = value;
                    this.RaisePropertyChanged("SortExpression");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyAnswerCriteria", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyAnswerCriteria : Epi.ImportExport.SurveyManagerService.Criteria {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GetAllColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeOrderStatisticsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeleteModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDownLoadFromAppField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDraftModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEditModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSqlProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OrganizationKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentResponseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReturnSizeInfoOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchCriteriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortfieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SurveyAnswerIdListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserOrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserPublishKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCompleted {
            get {
                return this.DateCompletedField;
            }
            set {
                if ((this.DateCompletedField.Equals(value) != true)) {
                    this.DateCompletedField = value;
                    this.RaisePropertyChanged("DateCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GetAllColumns {
            get {
                return this.GetAllColumnsField;
            }
            set {
                if ((this.GetAllColumnsField.Equals(value) != true)) {
                    this.GetAllColumnsField = value;
                    this.RaisePropertyChanged("GetAllColumns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeOrderStatistics {
            get {
                return this.IncludeOrderStatisticsField;
            }
            set {
                if ((this.IncludeOrderStatisticsField.Equals(value) != true)) {
                    this.IncludeOrderStatisticsField = value;
                    this.RaisePropertyChanged("IncludeOrderStatistics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChild {
            get {
                return this.IsChildField;
            }
            set {
                if ((this.IsChildField.Equals(value) != true)) {
                    this.IsChildField = value;
                    this.RaisePropertyChanged("IsChild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleteMode {
            get {
                return this.IsDeleteModeField;
            }
            set {
                if ((this.IsDeleteModeField.Equals(value) != true)) {
                    this.IsDeleteModeField = value;
                    this.RaisePropertyChanged("IsDeleteMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDownLoadFromApp {
            get {
                return this.IsDownLoadFromAppField;
            }
            set {
                if ((this.IsDownLoadFromAppField.Equals(value) != true)) {
                    this.IsDownLoadFromAppField = value;
                    this.RaisePropertyChanged("IsDownLoadFromApp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDraftMode {
            get {
                return this.IsDraftModeField;
            }
            set {
                if ((this.IsDraftModeField.Equals(value) != true)) {
                    this.IsDraftModeField = value;
                    this.RaisePropertyChanged("IsDraftMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEditMode {
            get {
                return this.IsEditModeField;
            }
            set {
                if ((this.IsEditModeField.Equals(value) != true)) {
                    this.IsEditModeField = value;
                    this.RaisePropertyChanged("IsEditMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMobile {
            get {
                return this.IsMobileField;
            }
            set {
                if ((this.IsMobileField.Equals(value) != true)) {
                    this.IsMobileField = value;
                    this.RaisePropertyChanged("IsMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSqlProject {
            get {
                return this.IsSqlProjectField;
            }
            set {
                if ((this.IsSqlProjectField.Equals(value) != true)) {
                    this.IsSqlProjectField = value;
                    this.RaisePropertyChanged("IsSqlProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OrganizationKey {
            get {
                return this.OrganizationKeyField;
            }
            set {
                if ((this.OrganizationKeyField.Equals(value) != true)) {
                    this.OrganizationKeyField = value;
                    this.RaisePropertyChanged("OrganizationKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentResponseId {
            get {
                return this.ParentResponseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentResponseIdField, value) != true)) {
                    this.ParentResponseIdField = value;
                    this.RaisePropertyChanged("ParentResponseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnSizeInfoOnly {
            get {
                return this.ReturnSizeInfoOnlyField;
            }
            set {
                if ((this.ReturnSizeInfoOnlyField.Equals(value) != true)) {
                    this.ReturnSizeInfoOnlyField = value;
                    this.RaisePropertyChanged("ReturnSizeInfoOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchCriteria {
            get {
                return this.SearchCriteriaField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchCriteriaField, value) != true)) {
                    this.SearchCriteriaField = value;
                    this.RaisePropertyChanged("SearchCriteria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.SortOrderField, value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sortfield {
            get {
                return this.SortfieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SortfieldField, value) != true)) {
                    this.SortfieldField = value;
                    this.RaisePropertyChanged("Sortfield");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SurveyAnswerIdList {
            get {
                return this.SurveyAnswerIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyAnswerIdListField, value) != true)) {
                    this.SurveyAnswerIdListField = value;
                    this.RaisePropertyChanged("SurveyAnswerIdList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyId {
            get {
                return this.SurveyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyIdField, value) != true)) {
                    this.SurveyIdField = value;
                    this.RaisePropertyChanged("SurveyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserOrganizationId {
            get {
                return this.UserOrganizationIdField;
            }
            set {
                if ((this.UserOrganizationIdField.Equals(value) != true)) {
                    this.UserOrganizationIdField = value;
                    this.RaisePropertyChanged("UserOrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserPublishKey {
            get {
                return this.UserPublishKeyField;
            }
            set {
                if ((this.UserPublishKeyField.Equals(value) != true)) {
                    this.UserPublishKeyField = value;
                    this.RaisePropertyChanged("UserPublishKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HttpPostedFileBase", Namespace="http://schemas.datacontract.org/2004/07/System.Web")]
    [System.SerializableAttribute()]
    public partial class HttpPostedFileBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationDTO", Namespace="http://schemas.datacontract.org/2004/07/Epi.Web.Common.DTO")]
    [System.SerializableAttribute()]
    public partial class OrganizationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEnabled {
            get {
                return this.IsEnabledField;
            }
            set {
                if ((this.IsEnabledField.Equals(value) != true)) {
                    this.IsEnabledField = value;
                    this.RaisePropertyChanged("IsEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationKey {
            get {
                return this.OrganizationKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationKeyField, value) != true)) {
                    this.OrganizationKeyField = value;
                    this.RaisePropertyChanged("OrganizationKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyAnswerDTO", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyAnswerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDraftModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RecordBeforeFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordSourceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RelateParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyAnswerDTO[] ResponseHierarchyIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> SqlDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurveyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserPublishKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViewIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCompleted {
            get {
                return this.DateCompletedField;
            }
            set {
                if ((this.DateCompletedField.Equals(value) != true)) {
                    this.DateCompletedField = value;
                    this.RaisePropertyChanged("DateCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdated {
            get {
                return this.DateUpdatedField;
            }
            set {
                if ((this.DateUpdatedField.Equals(value) != true)) {
                    this.DateUpdatedField = value;
                    this.RaisePropertyChanged("DateUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDraftMode {
            get {
                return this.IsDraftModeField;
            }
            set {
                if ((this.IsDraftModeField.Equals(value) != true)) {
                    this.IsDraftModeField = value;
                    this.RaisePropertyChanged("IsDraftMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentRecordId {
            get {
                return this.ParentRecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentRecordIdField, value) != true)) {
                    this.ParentRecordIdField = value;
                    this.RaisePropertyChanged("ParentRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RecordBeforeFlag {
            get {
                return this.RecordBeforeFlagField;
            }
            set {
                if ((this.RecordBeforeFlagField.Equals(value) != true)) {
                    this.RecordBeforeFlagField = value;
                    this.RaisePropertyChanged("RecordBeforeFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordSourceId {
            get {
                return this.RecordSourceIdField;
            }
            set {
                if ((this.RecordSourceIdField.Equals(value) != true)) {
                    this.RecordSourceIdField = value;
                    this.RaisePropertyChanged("RecordSourceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelateParentId {
            get {
                return this.RelateParentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RelateParentIdField, value) != true)) {
                    this.RelateParentIdField = value;
                    this.RaisePropertyChanged("RelateParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyAnswerDTO[] ResponseHierarchyIds {
            get {
                return this.ResponseHierarchyIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseHierarchyIdsField, value) != true)) {
                    this.ResponseHierarchyIdsField = value;
                    this.RaisePropertyChanged("ResponseHierarchyIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseId {
            get {
                return this.ResponseIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseIdField, value) != true)) {
                    this.ResponseIdField = value;
                    this.RaisePropertyChanged("ResponseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> SqlData {
            get {
                return this.SqlDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SqlDataField, value) != true)) {
                    this.SqlDataField = value;
                    this.RaisePropertyChanged("SqlData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SurveyId {
            get {
                return this.SurveyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyIdField, value) != true)) {
                    this.SurveyIdField = value;
                    this.RaisePropertyChanged("SurveyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserPublishKey {
            get {
                return this.UserPublishKeyField;
            }
            set {
                if ((this.UserPublishKeyField.Equals(value) != true)) {
                    this.UserPublishKeyField = value;
                    this.RaisePropertyChanged("UserPublishKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewId {
            get {
                return this.ViewIdField;
            }
            set {
                if ((this.ViewIdField.Equals(value) != true)) {
                    this.ViewIdField = value;
                    this.RaisePropertyChanged("ViewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XML {
            get {
                return this.XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLField, value) != true)) {
                    this.XMLField = value;
                    this.RaisePropertyChanged("XML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.SurveyInfoResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.OrganizationResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.SurveyAnswerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Epi.ImportExport.SurveyManagerService.PublishResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.AcknowledgeType AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReservationExpiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReservationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsAffectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.AcknowledgeType Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Build {
            get {
                return this.BuildField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildField, value) != true)) {
                    this.BuildField = value;
                    this.RaisePropertyChanged("Build");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIdField, value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReservationExpires {
            get {
                return this.ReservationExpiresField;
            }
            set {
                if ((this.ReservationExpiresField.Equals(value) != true)) {
                    this.ReservationExpiresField = value;
                    this.RaisePropertyChanged("ReservationExpires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationId {
            get {
                return this.ReservationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationIdField, value) != true)) {
                    this.ReservationIdField = value;
                    this.RaisePropertyChanged("ReservationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsAffected {
            get {
                return this.RowsAffectedField;
            }
            set {
                if ((this.RowsAffectedField.Equals(value) != true)) {
                    this.RowsAffectedField = value;
                    this.RaisePropertyChanged("RowsAffected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyInfoResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyInfoResponse : Epi.ImportExport.SurveyManagerService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyInfoDTO[] SurveyInfoListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPages {
            get {
                return this.NumberOfPagesField;
            }
            set {
                if ((this.NumberOfPagesField.Equals(value) != true)) {
                    this.NumberOfPagesField = value;
                    this.RaisePropertyChanged("NumberOfPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyInfoDTO[] SurveyInfoList {
            get {
                return this.SurveyInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyInfoListField, value) != true)) {
                    this.SurveyInfoListField = value;
                    this.RaisePropertyChanged("SurveyInfoList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganizationResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class OrganizationResponse : Epi.ImportExport.SurveyManagerService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Message1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.OrganizationDTO[] OrganizationListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Message")]
        public string Message1 {
            get {
                return this.Message1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Message1Field, value) != true)) {
                    this.Message1Field = value;
                    this.RaisePropertyChanged("Message1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.OrganizationDTO[] OrganizationList {
            get {
                return this.OrganizationListField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationListField, value) != true)) {
                    this.OrganizationListField = value;
                    this.RaisePropertyChanged("OrganizationList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurveyAnswerResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class SurveyAnswerResponse : Epi.ImportExport.SurveyManagerService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyInfoDTO SurveyInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.SurveyAnswerDTO[] SurveyResponseListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPages {
            get {
                return this.NumberOfPagesField;
            }
            set {
                if ((this.NumberOfPagesField.Equals(value) != true)) {
                    this.NumberOfPagesField = value;
                    this.RaisePropertyChanged("NumberOfPages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfResponses {
            get {
                return this.NumberOfResponsesField;
            }
            set {
                if ((this.NumberOfResponsesField.Equals(value) != true)) {
                    this.NumberOfResponsesField = value;
                    this.RaisePropertyChanged("NumberOfResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyInfoDTO SurveyInfo {
            get {
                return this.SurveyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyInfoField, value) != true)) {
                    this.SurveyInfoField = value;
                    this.RaisePropertyChanged("SurveyInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.SurveyAnswerDTO[] SurveyResponseList {
            get {
                return this.SurveyResponseListField;
            }
            set {
                if ((object.ReferenceEquals(this.SurveyResponseListField, value) != true)) {
                    this.SurveyResponseListField = value;
                    this.RaisePropertyChanged("SurveyResponseList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublishResponse", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class PublishResponse : Epi.ImportExport.SurveyManagerService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Epi.ImportExport.SurveyManagerService.PublishInfoDTO PublishInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Epi.ImportExport.SurveyManagerService.PublishInfoDTO PublishInfo {
            get {
                return this.PublishInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishInfoField, value) != true)) {
                    this.PublishInfoField = value;
                    this.RaisePropertyChanged("PublishInfo");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcknowledgeType", Namespace="http://www.yourcompany.com/types/")]
    public enum AcknowledgeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublishInfoDTO", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class PublishInfoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPulishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, string> ViewIdAndFormIdListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPulished {
            get {
                return this.IsPulishedField;
            }
            set {
                if ((this.IsPulishedField.Equals(value) != true)) {
                    this.IsPulishedField = value;
                    this.RaisePropertyChanged("IsPulished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusText {
            get {
                return this.StatusTextField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusTextField, value) != true)) {
                    this.StatusTextField = value;
                    this.RaisePropertyChanged("StatusText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> ViewIdAndFormIdList {
            get {
                return this.ViewIdAndFormIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewIdAndFormIdListField, value) != true)) {
                    this.ViewIdAndFormIdListField = value;
                    this.RaisePropertyChanged("ViewIdAndFormIdList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
    [System.SerializableAttribute()]
    public partial class CustomFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HelpLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HelpLink {
            get {
                return this.HelpLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.HelpLinkField, value) != true)) {
                    this.HelpLinkField = value;
                    this.RaisePropertyChanged("HelpLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SurveyManagerService.IManagerService")]
    public interface IManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/PublishSurvey", ReplyAction="http://tempuri.org/IManagerService/PublishSurveyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/PublishSurveyCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.PublishResponse PublishSurvey(Epi.ImportExport.SurveyManagerService.PublishRequest pRequestMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/GetSurveyInfo", ReplyAction="http://tempuri.org/IManagerService/GetSurveyInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/GetSurveyInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.SurveyInfoResponse GetSurveyInfo(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/GetOrganization", ReplyAction="http://tempuri.org/IManagerService/GetOrganizationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/GetOrganizationCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganization(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/GetOrganizationInfo", ReplyAction="http://tempuri.org/IManagerService/GetOrganizationInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/GetOrganizationInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganizationInfo(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/GetOrganizationNames", ReplyAction="http://tempuri.org/IManagerService/GetOrganizationNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/GetOrganizationNamesCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganizationNames(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/GetOrganizationByKey", ReplyAction="http://tempuri.org/IManagerService/GetOrganizationByKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/GetOrganizationByKeyCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganizationByKey(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/SetSurveyInfo", ReplyAction="http://tempuri.org/IManagerService/SetSurveyInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/SetSurveyInfoCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.SurveyInfoResponse SetSurveyInfo(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/GetSurveyAnswer", ReplyAction="http://tempuri.org/IManagerService/GetSurveyAnswerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/GetSurveyAnswerCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.SurveyAnswerResponse GetSurveyAnswer(Epi.ImportExport.SurveyManagerService.SurveyAnswerRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/SetOrganization", ReplyAction="http://tempuri.org/IManagerService/SetOrganizationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/SetOrganizationCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.OrganizationResponse SetOrganization(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/UpdateOrganizationInfo", ReplyAction="http://tempuri.org/IManagerService/UpdateOrganizationInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/UpdateOrganizationInfoCustomFaultExceptionFaul" +
            "t", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.OrganizationResponse UpdateOrganizationInfo(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/IsValidOrgKey", ReplyAction="http://tempuri.org/IManagerService/IsValidOrgKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/IsValidOrgKeyCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        bool IsValidOrgKey(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagerService/RePublishSurvey", ReplyAction="http://tempuri.org/IManagerService/RePublishSurveyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Epi.ImportExport.SurveyManagerService.CustomFaultException), Action="http://tempuri.org/IManagerService/RePublishSurveyCustomFaultExceptionFault", Name="CustomFaultException", Namespace="http://www.yourcompany.com/types/")]
        Epi.ImportExport.SurveyManagerService.PublishResponse RePublishSurvey(Epi.ImportExport.SurveyManagerService.PublishRequest pRequestMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagerServiceChannel : Epi.ImportExport.SurveyManagerService.IManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagerServiceClient : System.ServiceModel.ClientBase<Epi.ImportExport.SurveyManagerService.IManagerService>, Epi.ImportExport.SurveyManagerService.IManagerService {
        
        public ManagerServiceClient() {
        }
        
        public ManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Epi.ImportExport.SurveyManagerService.PublishResponse PublishSurvey(Epi.ImportExport.SurveyManagerService.PublishRequest pRequestMessage) {
            return base.Channel.PublishSurvey(pRequestMessage);
        }
        
        public Epi.ImportExport.SurveyManagerService.SurveyInfoResponse GetSurveyInfo(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest pRequest) {
            return base.Channel.GetSurveyInfo(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganization(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest) {
            return base.Channel.GetOrganization(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganizationInfo(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest) {
            return base.Channel.GetOrganizationInfo(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganizationNames(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest) {
            return base.Channel.GetOrganizationNames(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.OrganizationResponse GetOrganizationByKey(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest) {
            return base.Channel.GetOrganizationByKey(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.SurveyInfoResponse SetSurveyInfo(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest pRequest) {
            return base.Channel.SetSurveyInfo(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.SurveyAnswerResponse GetSurveyAnswer(Epi.ImportExport.SurveyManagerService.SurveyAnswerRequest pRequest) {
            return base.Channel.GetSurveyAnswer(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.OrganizationResponse SetOrganization(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest) {
            return base.Channel.SetOrganization(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.OrganizationResponse UpdateOrganizationInfo(Epi.ImportExport.SurveyManagerService.OrganizationRequest pRequest) {
            return base.Channel.UpdateOrganizationInfo(pRequest);
        }
        
        public bool IsValidOrgKey(Epi.ImportExport.SurveyManagerService.SurveyInfoRequest pRequest) {
            return base.Channel.IsValidOrgKey(pRequest);
        }
        
        public Epi.ImportExport.SurveyManagerService.PublishResponse RePublishSurvey(Epi.ImportExport.SurveyManagerService.PublishRequest pRequestMessage) {
            return base.Channel.RePublishSurvey(pRequestMessage);
        }
    }
}
