//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Windows.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epi.Windows.Globalization.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding.
        /// </summary>
        internal static string ADDING_SPACE {
            get {
                return ResourceManager.GetString("ADDING_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic translation is not supported for the selected language..
        /// </summary>
        internal static string CANNOT_AUTO_TRANSLATE {
            get {
                return ResourceManager.GetString("CANNOT_AUTO_TRANSLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        internal static string COMPLETE_PERIOD {
            get {
                return ResourceManager.GetString("COMPLETE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected language and delete all language files? Note: this action cannot be undone..
        /// </summary>
        internal static string CONFIRM_LANGUAGE_DELETION {
            get {
                return ResourceManager.GetString("CONFIRM_LANGUAGE_DELETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted all rows from master resource table..
        /// </summary>
        internal static string DELETED_ALL_ROWS {
            get {
                return ResourceManager.GetString("DELETED_ALL_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting existing records..
        /// </summary>
        internal static string DELETING_EXISTING_RECORDS {
            get {
                return ResourceManager.GetString("DELETING_EXISTING_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed extraction of {0} resource strings..
        /// </summary>
        internal static string EXTRACTION_COMPLETE {
            get {
                return ResourceManager.GetString("EXTRACTION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} strings extracted from {0}.
        /// </summary>
        internal static string EXTRACTION_COUNT {
            get {
                return ResourceManager.GetString("EXTRACTION_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found existing language: &apos;{0}&apos;..
        /// </summary>
        internal static string FOUND_LANGUAGE {
            get {
                return ResourceManager.GetString("FOUND_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos; language:.
        /// </summary>
        internal static string INSTALLING_LANGUAGE {
            get {
                return ResourceManager.GetString("INSTALLING_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid build folder specified..
        /// </summary>
        internal static string INVALID_BUILD_FOLDER {
            get {
                return ResourceManager.GetString("INVALID_BUILD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted language folder &apos;{0}&apos;..
        /// </summary>
        internal static string LANGUAGE_DELETION_CONFIRM {
            get {
                return ResourceManager.GetString("LANGUAGE_DELETION_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} resources from database..
        /// </summary>
        internal static string LOADED_RESOURCES {
            get {
                return ResourceManager.GetString("LOADED_RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No languages found..
        /// </summary>
        internal static string NO_LANGUAGES_FOUND {
            get {
                return ResourceManager.GetString("NO_LANGUAGES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed compiled satellite assembly &apos;{0}&apos;..
        /// </summary>
        internal static string SATELLITE_INSTALLATION {
            get {
                return ResourceManager.GetString("SATELLITE_INSTALLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for languages in &apos;{0}&apos;.
        /// </summary>
        internal static string SEARCHING_LANGUAGES {
            get {
                return ResourceManager.GetString("SEARCHING_LANGUAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating &apos;{0}&apos;.
        /// </summary>
        internal static string TRANSLATING {
            get {
                return ResourceManager.GetString("TRANSLATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
    }
}
