//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.ImportExport.ProjectPackagers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnpackagerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnpackagerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epi.ImportExport.ProjectPackagers.UnpackagerStrings", typeof(UnpackagerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import completed for data package {0}..
        /// </summary>
        internal static string IMPORT_END {
            get {
                return ResourceManager.GetString("IMPORT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished importing records from package {0} into form {1}. Records updated: {2}. Records appended: {3}..
        /// </summary>
        internal static string IMPORT_END_FORM {
            get {
                return ResourceManager.GetString("IMPORT_END_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing field data from package ({0})....
        /// </summary>
        internal static string IMPORT_FIELD_PROGRESS {
            get {
                return ResourceManager.GetString("IMPORT_FIELD_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing grid data from package ({0})....
        /// </summary>
        internal static string IMPORT_GRID_PROGRESS {
            get {
                return ResourceManager.GetString("IMPORT_GRID_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import initiated for data package {0} by user {1}..
        /// </summary>
        internal static string IMPORT_INITIATED {
            get {
                return ResourceManager.GetString("IMPORT_INITIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started importing records from package {0} into form {1}..
        /// </summary>
        internal static string IMPORT_START_FORM {
            get {
                return ResourceManager.GetString("IMPORT_START_FORM", resourceCulture);
            }
        }
    }
}
