//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatCalc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatCalcSharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatCalcSharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatCalc.StatCalcSharedStrings", typeof(StatCalcSharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHI SQUARE
        ///FOR TREND.
        /// </summary>
        internal static string STATCALC_CHI_SQUARE {
            get {
                return ResourceManager.GetString("STATCALC_CHI_SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COHORT OR
        ///CROSS-SECTIONAL.
        /// </summary>
        internal static string STATCALC_COHORT_CROSS {
            get {
                return ResourceManager.GetString("STATCALC_COHORT_CROSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE:.
        /// </summary>
        internal static string STATCALC_LANGUAGE {
            get {
                return ResourceManager.GetString("STATCALC_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHED PAIR
        ///CASE CONTROL STUDY.
        /// </summary>
        internal static string STATCALC_MATCHED_PAIR_CASE {
            get {
                return ResourceManager.GetString("STATCALC_MATCHED_PAIR_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POISSON
        ///(RARE EVENT VS. STD).
        /// </summary>
        internal static string STATCALC_POISSON_RARE {
            get {
                return ResourceManager.GetString("STATCALC_POISSON_RARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULATION BINOMIAL
        ///(PROPORTION VS. STD.).
        /// </summary>
        internal static string STATCALC_POPULATION_BINOMIAL {
            get {
                return ResourceManager.GetString("STATCALC_POPULATION_BINOMIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULATION SURVEY.
        /// </summary>
        internal static string STATCALC_POPULATION_SURVEY {
            get {
                return ResourceManager.GetString("STATCALC_POPULATION_SURVEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLES (2 x 2 x N).
        /// </summary>
        internal static string STATCALC_TABLES_22N {
            get {
                return ResourceManager.GetString("STATCALC_TABLES_22N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNMATCHED
        ///CASE-CONTROL.
        /// </summary>
        internal static string STATCALC_UNMATCHED_CASE {
            get {
                return ResourceManager.GetString("STATCALC_UNMATCHED_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION:.
        /// </summary>
        internal static string STATCALC_VERSION {
            get {
                return ResourceManager.GetString("STATCALC_VERSION", resourceCulture);
            }
        }
    }
}
