# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.8
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dependencies
      run: dotnet add package Newtonsoft.Json --version 13.0.1
    - name: Build
      run: dotnet build --no-restore --verbosity diagnostic
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
